G_WIDTH = 1920;
G_HEIGHT = 1080;
G_MOBILE_WIDTH = 800;
G_FPS = 50;
G_PIXEL_1M = 300;
G_MIX_DURATION = 0.2;
G_MIX_DURATION_FOR_TALANT = 0;

G_REPLAY_MOTION_RATE = 0.25;
G_REPLAY_TRIGGER_TIME = 0.1;
G_REPLAY_START_BUFFER = 1.5;
G_REPLAY_END_BUFFER = 1.0;

BASE_URL_PROD = "https://api.chickenderby.com";
BASE_URL_DEV = "https://api-dev.chickenderby.com";
BASE_URL_LOCAL = "http://localhost:8081";

C_STATUS_IDLE = 0;
C_STATUS_RUN = 1;
C_STATUS_FAST_RUN = 2;
C_STATUS_ARRIVED = 3;

C_BODY_CHICKEN = 0;
C_BODY_DRAGON = 1;
